--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -30,8 +30,8 @@
  obj-$(CONFIG_ARCH_MSM8960) += board-msm8960.o devices-msm8960.o
 
  obj-$(CONFIG_ARCH_MSM7X30) += gpiomux-v1.o gpiomux.o
-obj-$(CONFIG_ARCH_QSD8X50) += gpiomux-8x50.o gpiomux-v1.o gpiomux.o
-obj-$(CONFIG_ARCH_MSM8X60) += gpiomux-8x60.o gpiomux-v2.o gpiomux.o
+obj-$(CONFIG_ARCH_QSD8X50) += gpiomux-v1.o gpiomux.o
+obj-$(CONFIG_ARCH_MSM8X60) += gpiomux-v2.o gpiomux.o
  ifdef CONFIG_MSM_V2_TLMM
  ifndef CONFIG_ARCH_MSM8960
  # TODO: TLMM Mapping issues need to be resolved
